// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	ID          string `json:"id" bson:"_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type NewCourse struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type UpdateCourse struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"Name"`
}
